<div class="row">
    <div class="col-md-12">
        <div class="jumbotron">
            <div class="jumbotron-contents">
                <h1><?php echo sprintf($this->translate('Watch video together')) ?></h1>
                <p><a class="btn btn-primary" href="/room"><?php echo $this->translate('Launch the demo') ?></a></p>
            </div>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Rooms') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Create a room yourself, or join someone else. Up to 40 users.')) ?></p>
           </div>
        </div>
    </div>



    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Synced') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The stream is synced with timestamps. So you will see exactly what everyone else sees!')) ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Energy bar') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('As an anti-spam measurement every user has an energy bar. It repleshes over time. Adding and removing videos cost points so use it carefully!')) ?></p>
              </div>
        </div>
    </div>
</div>
